
version: "3.7"
services:
  kafka:
    build: https://github.com/6za/kafka-dockerfile.git
    restart: 'unless-stopped'
    environment:
      - LOG_DIR=/data/persitence
    command: bash -c "/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties"
    ports:
      - "9092:9092"
    volumes:
      - /home/pi/docker_host/persisted/kafka:/data/persitence
