FROM ubuntu:16.04

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-armhf
 
 
# install packages
RUN \
  apt-get update && apt-get install -y \
  ssh \
  rsync \
  vim inetutils-ping telnet\
  openjdk-8-jdk \
  wget libzip4 libsnappy1v5 libssl-dev && \
  rm -rf /var/lib/apt/lists/* 
